### PR TITLE
Add integration packages to the monorepo

### LINKED ISSUE #186: Bring integrations into the main repo

### PR DESCRIPTION
**Pull request by matthewp**
Integrations

- [x] preact-robot
- [x] robot-hooks
- [x] haunted-robot
- [x] react-robot
- [x] lit-robot

Closes #186

### CODE REVIEW

**Comment by matthewp** [comment]
All of  the packages are added. Now I need to go through and upgrade all of the dependencies and create changesets for everything.

**Comment by matthewp** [comment]
@gkiely this is ready for review

**Review by gkiely — APPROVED** [review]
Looks good to me 👍

**Comment by matthewp** [comment]
Thanks! I merge later when I have time to update all of the repos to point people towards here.

**Pull request merged**
