### PR TITLE
Fix: check nested machines to be in final state

### LINKED ISSUE #100: [bug] Nested tree machines final state
When there is a tree of nested state machines, when the very child final state is reached it goes straight to the root machine

### PR DESCRIPTION
**Pull request by kybarg**
fixes #100 #101 in elegant way
with `Object.is(this.child, s)` we make sure there is no more nested not resolved machines left and machines gonna resolve starting from the deepest level up to top

### CODE REVIEW

**Comment by matthewp** [comment]
Can we save bytes by using triple equals instead?

**Comment by matthewp** [comment]
Actually if comparing objects double equal is fine.

**Comment by kybarg** [comment]
@matthewp done

**Comment by matthewp** [comment]
Awesome, thanks!

**Comment by matthewp** [comment]
Released here: https://github.com/matthewp/robot/releases/tag/v0.2.14

Thanks again!

**Pull request merged**
